### ISSUE TITLE
no Module

### ISSUE THREAD

**Issue by forbesus** [Youngestdev/async-fastapi-mongo#9]
I am trying to run server, But I have got the following error
 from app.server.routes.studento\app\server\app.py", line 3, in < import router as StudentRouter   
ModuleNotFoundError: No module nam import router as StudentRouter   ed 'app'

**Comment by BeardedShamrock** [comment]
the same trouble, need to convert path:

app.py 
from .routes.student import router as StudentRouter

and in routes:

from ..database import (
    add_student,
    delete_student,
    retrieve_student,
    retrieve_students,
    update_student,
)
from ..models.student import (
    ErrorResponseModel,
    ResponseModel,
    StudentSchema,
    UpdateStudentModel,
)

**Comment by adolfojmnz** [comment]
This issue should be closed as the error `ModuleNotFoundError` got solved in [PR#10](https://github.com/Youngestdev/async-fastapi-mongo/pull/10)

**Comment by forbesus** [comment]
thank you
